# Generated by Django 5.0.6 on 2024-06-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_created_professores_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Faculdades',
            new_name='Faculdade',
        ),
    ]
